/**
 * Integration tests for the memory schema migration (0003_memory_tables.sql).
 *
 * Verifies all 9 tables (node, edge, episode, episode_node, core_memory,
 * core_memory_changelog, user_model_dimension, self_model_domain, skill),
 * their constraints, triggers, indexes, and ON DELETE behaviors.
 *
 * Requires Docker PostgreSQL running via `just up`.
 */

import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import type { Pool } from "../../src/db/pool.ts";
import { createTestPool } from "../helpers.ts";

let pool: Pool;

beforeAll(async () => {
	pool = createTestPool();
	const connectResult = await pool.connect();
	if (!connectResult.ok) {
		throw new Error(`Test setup failed: ${connectResult.error.message}`);
	}

	// Schema is set up by `just test-db` before bun test starts.
	// Clean test data from previous runs (keep tables and seeds intact).
	// core_memory is excluded — it contains seeded rows verified by tests.
	await pool.sql`TRUNCATE node, edge, episode, episode_node, core_memory_changelog, user_model_dimension, self_model_domain, skill CASCADE`;
});

afterAll(async () => {
	if (pool) {
		await pool.end();
	}
});

// ---------------------------------------------------------------------------
// Table Existence
// ---------------------------------------------------------------------------

describe("tables created", () => {
	const expectedTables = [
		"node",
		"edge",
		"episode",
		"episode_node",
		"core_memory",
		"core_memory_changelog",
		"user_model_dimension",
		"self_model_domain",
		"skill",
	];

	test("all 9 memory tables exist", async () => {
		const rows = await pool.sql`
			SELECT table_name
			FROM information_schema.tables
			WHERE table_schema = 'public'
			  AND table_type = 'BASE TABLE'
			ORDER BY table_name
		`;
		const tableNames = rows.map((r) => String(r["table_name"]));
		for (const t of expectedTables) {
			expect(tableNames).toContain(t);
		}
	});
});

// ---------------------------------------------------------------------------
// Node Tests
// ---------------------------------------------------------------------------

describe("node", () => {
	test("tsvector trigger populates search_text on INSERT", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body)
			VALUES ('fact', 'The quick brown fox jumps over the lazy dog')
			RETURNING search_text
		`;
		const searchText = String(rows[0]?.["search_text"]);
		// tsvector should contain stemmed tokens
		expect(searchText).toContain("quick");
		expect(searchText).toContain("brown");
		expect(searchText).toContain("fox");
	});

	test("access_count defaults to 0 and last_accessed_at defaults to NULL", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body)
			VALUES ('fact', 'Access count test node')
			RETURNING access_count, last_accessed_at
		`;
		expect(rows[0]?.["access_count"]).toBe(0);
		expect(rows[0]?.["last_accessed_at"]).toBeNull();
	});

	test("explicit ID insert succeeds (GENERATED BY DEFAULT)", async () => {
		const explicitId = 99999;
		const rows = await pool.sql`
			INSERT INTO node (id, kind, body)
			VALUES (${explicitId}, 'fact', 'Explicit ID node')
			RETURNING id
		`;
		expect(rows[0]?.["id"]).toBe(explicitId);

		// Cleanup
		await pool.sql`DELETE FROM node WHERE id = ${explicitId}`;
	});

	test("kind = 'pattern' is accepted", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body)
			VALUES ('pattern', 'A recurring pattern')
			RETURNING id, kind
		`;
		expect(rows[0]?.["kind"]).toBe("pattern");
	});

	test("kind = 'principle' is accepted", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body)
			VALUES ('principle', 'A guiding principle')
			RETURNING id, kind
		`;
		expect(rows[0]?.["kind"]).toBe("principle");
	});

	test("tsvector trigger updates search_text on UPDATE", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body)
			VALUES ('fact', 'Original body text')
			RETURNING id
		`;
		const nodeId = Number(rows[0]?.["id"]);

		const updated = await pool.sql`
			UPDATE node SET body = 'Completely new updated body text'
			WHERE id = ${nodeId}
			RETURNING search_text
		`;
		const searchText = String(updated[0]?.["search_text"]);
		expect(searchText).toContain("complet");
		expect(searchText).toContain("new");
		expect(searchText).not.toContain("origin");
	});

	test("updated_at changes on content UPDATE", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body)
			VALUES ('fact', 'Content update test')
			RETURNING id, extract(epoch FROM updated_at) AS epoch
		`;
		const nodeId = Number(rows[0]?.["id"]);
		const originalEpoch = Number(rows[0]?.["epoch"]);

		// pg_sleep ensures the database clock advances between transactions
		await pool.sql`SELECT pg_sleep(0.05)`;

		const updated = await pool.sql`
			UPDATE node SET body = 'Modified content' WHERE id = ${nodeId}
			RETURNING extract(epoch FROM updated_at) AS epoch
		`;
		const newEpoch = Number(updated[0]?.["epoch"]);
		expect(newEpoch).toBeGreaterThan(originalEpoch);
	});

	test("updated_at does NOT change on access_count/last_accessed_at UPDATE", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body)
			VALUES ('fact', 'Access tracking test')
			RETURNING id, extract(epoch FROM updated_at) AS epoch
		`;
		const nodeId = Number(rows[0]?.["id"]);
		const originalEpoch = Number(rows[0]?.["epoch"]);

		await pool.sql`SELECT pg_sleep(0.05)`;

		const updated = await pool.sql`
			UPDATE node
			SET access_count = access_count + 1, last_accessed_at = now()
			WHERE id = ${nodeId}
			RETURNING extract(epoch FROM updated_at) AS epoch
		`;
		const newEpoch = Number(updated[0]?.["epoch"]);
		expect(newEpoch).toBe(originalEpoch);
	});

	test("idx_node_kind index exists", async () => {
		const rows = await pool.sql`
			SELECT indexname FROM pg_indexes
			WHERE tablename = 'node' AND indexname = 'idx_node_kind'
		`;
		expect(rows).toHaveLength(1);
	});

	test("CHECK: rejects invalid kind", async () => {
		try {
			await pool.sql`INSERT INTO node (kind, body) VALUES ('invalid', 'bad kind')`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects confidence > 1.0", async () => {
		try {
			await pool.sql`INSERT INTO node (kind, body, confidence) VALUES ('fact', 'test', 1.5)`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects negative confidence", async () => {
		try {
			await pool.sql`INSERT INTO node (kind, body, confidence) VALUES ('fact', 'test', -0.1)`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects invalid trust", async () => {
		try {
			await pool.sql`INSERT INTO node (kind, body, trust) VALUES ('fact', 'test', 'bogus')`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects invalid sensitivity", async () => {
		try {
			await pool.sql`INSERT INTO node (kind, body, sensitivity) VALUES ('fact', 'test', 'secret')`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects importance > 1.0", async () => {
		try {
			await pool.sql`INSERT INTO node (kind, body, importance) VALUES ('fact', 'test', 2.0)`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	// Phase 13a additions
	test("metadata column defaults to empty object", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body) VALUES ('fact', 'Metadata default test')
			RETURNING metadata
		`;
		expect(rows[0]?.["metadata"]).toEqual({});
	});

	test("metadata column stores structured JSON", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body, metadata)
			VALUES ('person', 'Ada', ${pool.sql.json({ company: "Acme", role: "CTO" })})
			RETURNING metadata
		`;
		expect(rows[0]?.["metadata"]).toEqual({ company: "Acme", role: "CTO" });
	});

	test("source_event_id column defaults to NULL", async () => {
		const rows = await pool.sql`
			INSERT INTO node (kind, body) VALUES ('fact', 'Source event id default')
			RETURNING source_event_id
		`;
		expect(rows[0]?.["source_event_id"]).toBeNull();
	});

	test("idx_node_source_event partial index exists", async () => {
		const rows = await pool.sql`
			SELECT indexdef FROM pg_indexes
			WHERE tablename = 'node' AND indexname = 'idx_node_source_event'
		`;
		expect(rows).toHaveLength(1);
		expect(String(rows[0]?.["indexdef"])).toContain("source_event_id IS NOT NULL");
	});
});

// ---------------------------------------------------------------------------
// Edge Tests
// ---------------------------------------------------------------------------

describe("edge", () => {
	let sourceNodeId: number;
	let targetNodeId: number;

	beforeAll(async () => {
		const rowsA = await pool.sql`
			INSERT INTO node (kind, body) VALUES ('fact', 'Edge test node A') RETURNING id
		`;
		sourceNodeId = Number(rowsA[0]?.["id"]);

		const rowsB = await pool.sql`
			INSERT INTO node (kind, body) VALUES ('fact', 'Edge test node B') RETURNING id
		`;
		targetNodeId = Number(rowsB[0]?.["id"]);
	});

	test("FK constraint rejects invalid source_id", async () => {
		try {
			await pool.sql`INSERT INTO edge (source_id, target_id, label) VALUES (999999, ${targetNodeId}, 'related_to')`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects weight > 5.0", async () => {
		try {
			await pool.sql`INSERT INTO edge (source_id, target_id, label, weight) VALUES (${sourceNodeId}, ${targetNodeId}, 'test', 6.0)`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("active edge partial indexes exist", async () => {
		const rows = await pool.sql`
			SELECT indexname, indexdef FROM pg_indexes
			WHERE tablename = 'edge'
			  AND indexname IN ('idx_edge_source_active', 'idx_edge_target_active')
			ORDER BY indexname
		`;
		expect(rows).toHaveLength(2);
		expect(String(rows[0]?.["indexdef"])).toContain("valid_to IS NULL");
		expect(String(rows[1]?.["indexdef"])).toContain("valid_to IS NULL");
	});

	test("unique active edge index prevents duplicates", async () => {
		await pool.sql`
			INSERT INTO edge (source_id, target_id, label)
			VALUES (${sourceNodeId}, ${targetNodeId}, 'related_to')
		`;
		try {
			await pool.sql`
				INSERT INTO edge (source_id, target_id, label)
				VALUES (${sourceNodeId}, ${targetNodeId}, 'related_to')
			`;
			expect.unreachable("should have thrown on duplicate active edge");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("ON DELETE CASCADE removes edges when node is deleted", async () => {
		// Create a pair of nodes with an edge
		const srcRows = await pool.sql`
			INSERT INTO node (kind, body) VALUES ('fact', 'Cascade test A') RETURNING id
		`;
		const srcId = Number(srcRows[0]?.["id"]);

		const tgtRows = await pool.sql`
			INSERT INTO node (kind, body) VALUES ('fact', 'Cascade test B') RETURNING id
		`;
		const tgtId = Number(tgtRows[0]?.["id"]);

		await pool.sql`
			INSERT INTO edge (source_id, target_id, label)
			VALUES (${srcId}, ${tgtId}, 'test_cascade')
		`;

		// Delete source node — edge should be cascaded
		await pool.sql`DELETE FROM node WHERE id = ${srcId}`;

		const remaining = await pool.sql`
			SELECT id FROM edge WHERE source_id = ${srcId} OR target_id = ${srcId}
		`;
		expect(remaining).toHaveLength(0);

		// Cleanup
		await pool.sql`DELETE FROM node WHERE id = ${tgtId}`;
	});
});

// ---------------------------------------------------------------------------
// Episode Tests
// ---------------------------------------------------------------------------

describe("episode", () => {
	test("updated_at trigger fires on UPDATE", async () => {
		const rows = await pool.sql`
			INSERT INTO episode (session_id, role, body)
			VALUES ('sess-upd', 'user', 'Episode updated_at test')
			RETURNING id, extract(epoch FROM updated_at) AS epoch
		`;
		const episodeId = Number(rows[0]?.["id"]);
		const originalEpoch = Number(rows[0]?.["epoch"]);

		await pool.sql`SELECT pg_sleep(0.05)`;

		// Set superseded_by to self — a real state change (not a no-op)
		const updated = await pool.sql`
			UPDATE episode SET superseded_by = ${episodeId} WHERE id = ${episodeId}
			RETURNING extract(epoch FROM updated_at) AS epoch
		`;
		const newEpoch = Number(updated[0]?.["epoch"]);
		expect(newEpoch).toBeGreaterThan(originalEpoch);
	});

	test("CHECK: rejects invalid role", async () => {
		try {
			await pool.sql`INSERT INTO episode (session_id, role, body) VALUES ('sess-1', 'system', 'bad role')`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	// Phase 13a: episode.importance
	test("importance column defaults to 0.5", async () => {
		const rows = await pool.sql`
			INSERT INTO episode (session_id, role, body)
			VALUES ('sess-imp-default', 'user', 'Default importance test')
			RETURNING importance
		`;
		expect(rows[0]?.["importance"]).toBe(0.5);
	});

	test("importance CHECK rejects values > 1.0", async () => {
		try {
			await pool.sql`
				INSERT INTO episode (session_id, role, body, importance)
				VALUES ('sess-imp-high', 'user', 'bad', 1.5)
			`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("importance CHECK rejects negative values", async () => {
		try {
			await pool.sql`
				INSERT INTO episode (session_id, role, body, importance)
				VALUES ('sess-imp-neg', 'user', 'bad', -0.1)
			`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("idx_episode_importance partial index exists", async () => {
		const rows = await pool.sql`
			SELECT indexdef FROM pg_indexes
			WHERE tablename = 'episode' AND indexname = 'idx_episode_importance'
		`;
		expect(rows).toHaveLength(1);
		expect(String(rows[0]?.["indexdef"])).toContain("superseded_by IS NULL");
	});

	test("superseded_by ON DELETE SET NULL", async () => {
		// Create a consolidated episode
		const consolidated = await pool.sql`
			INSERT INTO episode (session_id, role, body)
			VALUES ('sess-1', 'assistant', 'Consolidated summary')
			RETURNING id
		`;
		const consolidatedId = Number(consolidated[0]?.["id"]);

		// Create original episode referencing the consolidated one
		const original = await pool.sql`
			INSERT INTO episode (session_id, role, body, superseded_by)
			VALUES ('sess-1', 'user', 'Original message', ${consolidatedId})
			RETURNING id
		`;
		const originalId = Number(original[0]?.["id"]);

		// Delete the consolidated episode
		await pool.sql`DELETE FROM episode WHERE id = ${consolidatedId}`;

		// Original's superseded_by should be NULL
		const check = await pool.sql`
			SELECT superseded_by FROM episode WHERE id = ${originalId}
		`;
		expect(check[0]?.["superseded_by"]).toBeNull();
	});
});

// ---------------------------------------------------------------------------
// Core Memory Tests
// ---------------------------------------------------------------------------

describe("core_memory", () => {
	test("seeded with 4 slots", async () => {
		const rows = await pool.sql`
			SELECT slot FROM core_memory ORDER BY slot
		`;
		expect(rows).toHaveLength(4);
		const slots = rows.map((r) => String(r["slot"]));
		expect(slots).toContain("persona");
		expect(slots).toContain("goals");
		expect(slots).toContain("user_model");
		expect(slots).toContain("context");
	});
});

// ---------------------------------------------------------------------------
// User Model Dimension Tests
// ---------------------------------------------------------------------------

describe("user_model_dimension", () => {
	test("CHECK: rejects confidence > 1.0", async () => {
		try {
			await pool.sql`INSERT INTO user_model_dimension (name, confidence) VALUES ('test_hi', 1.5)`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects confidence < 0.0", async () => {
		try {
			await pool.sql`INSERT INTO user_model_dimension (name, confidence) VALUES ('test_dim', -1.0)`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});
});

// ---------------------------------------------------------------------------
// Self Model Domain Tests
// ---------------------------------------------------------------------------

describe("self_model_domain", () => {
	test("CHECK: rejects correct > predictions", async () => {
		try {
			await pool.sql`
				INSERT INTO self_model_domain (name, predictions, correct)
				VALUES ('bad_domain', 5, 10)
			`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects negative predictions", async () => {
		try {
			await pool.sql`
				INSERT INTO self_model_domain (name, predictions, correct)
				VALUES ('neg_pred', -1, 0)
			`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects negative correct", async () => {
		try {
			await pool.sql`
				INSERT INTO self_model_domain (name, predictions, correct)
				VALUES ('neg_corr', 5, -1)
			`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("valid predictions and correct are accepted", async () => {
		const rows = await pool.sql`
			INSERT INTO self_model_domain (name, predictions, correct)
			VALUES ('valid_domain', 10, 7)
			RETURNING predictions, correct
		`;
		expect(rows[0]?.["predictions"]).toBe(10);
		expect(rows[0]?.["correct"]).toBe(7);
	});

	// Phase 13a: windowed calibration columns
	test("recent_predictions and recent_correct default to 0", async () => {
		const rows = await pool.sql`
			INSERT INTO self_model_domain (name) VALUES ('win_defaults')
			RETURNING recent_predictions, recent_correct, window_reset_at
		`;
		expect(rows[0]?.["recent_predictions"]).toBe(0);
		expect(rows[0]?.["recent_correct"]).toBe(0);
		expect(rows[0]?.["window_reset_at"]).toBeInstanceOf(Date);
	});

	test("CHECK: rejects recent_correct > recent_predictions", async () => {
		try {
			await pool.sql`
				INSERT INTO self_model_domain (name, recent_predictions, recent_correct)
				VALUES ('win_bad', 3, 5)
			`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects negative recent_predictions", async () => {
		try {
			await pool.sql`
				INSERT INTO self_model_domain (name, recent_predictions)
				VALUES ('win_neg_pred', -1)
			`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});

	test("CHECK: rejects negative recent_correct", async () => {
		try {
			await pool.sql`
				INSERT INTO self_model_domain (name, recent_predictions, recent_correct)
				VALUES ('win_neg_corr', 5, -1)
			`;
			expect.unreachable("should have thrown");
		} catch (e) {
			expect(e).toBeDefined();
		}
	});
});

// ---------------------------------------------------------------------------
// Skill Tests
// ---------------------------------------------------------------------------

describe("skill", () => {
	test("insert with defaults yields success_rate = 0.0", async () => {
		const rows = await pool.sql`
			INSERT INTO skill (name, trigger_context, strategy)
			VALUES ('test skill', 'when user asks about weather', 'check weather API')
			RETURNING success_rate
		`;
		expect(rows[0]?.["success_rate"]).toBe(0);
	});

	test("success_rate is computed correctly after update", async () => {
		const inserted = await pool.sql`
			INSERT INTO skill (name, trigger_context, strategy)
			VALUES ('rated skill', 'trigger', 'strategy')
			RETURNING id
		`;
		const skillId = Number(inserted[0]?.["id"]);

		await pool.sql`
			UPDATE skill SET success_count = 3, attempt_count = 4 WHERE id = ${skillId}
		`;

		const rows = await pool.sql`
			SELECT success_rate FROM skill WHERE id = ${skillId}
		`;
		expect(rows[0]?.["success_rate"]).toBeCloseTo(0.75, 5);
	});

	test("version lineage: parent_id FK works", async () => {
		const parent = await pool.sql`
			INSERT INTO skill (name, trigger_context, strategy)
			VALUES ('parent skill', 'trigger', 'strategy v1')
			RETURNING id
		`;
		const parentId = Number(parent[0]?.["id"]);

		const child = await pool.sql`
			INSERT INTO skill (name, trigger_context, strategy, parent_id, version)
			VALUES ('child skill', 'trigger', 'strategy v2', ${parentId}, 2)
			RETURNING id, parent_id
		`;
		expect(child[0]?.["parent_id"]).toBe(parentId);
	});

	test("parent ON DELETE SET NULL", async () => {
		const parent = await pool.sql`
			INSERT INTO skill (name, trigger_context, strategy)
			VALUES ('parent to delete', 'trigger', 'strategy')
			RETURNING id
		`;
		const parentId = Number(parent[0]?.["id"]);

		const child = await pool.sql`
			INSERT INTO skill (name, trigger_context, strategy, parent_id)
			VALUES ('orphaned child', 'trigger', 'strategy', ${parentId})
			RETURNING id
		`;
		const childId = Number(child[0]?.["id"]);

		// Delete parent
		await pool.sql`DELETE FROM skill WHERE id = ${parentId}`;

		// Child's parent_id should be NULL
		const check = await pool.sql`SELECT parent_id FROM skill WHERE id = ${childId}`;
		expect(check[0]?.["parent_id"]).toBeNull();
	});
});

// Idempotency is tested in tests/db/migrate.test.ts — not duplicated here.
