apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 30s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: sampled_trace_id
          matcherType: label
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlDisplayLabel: Open trace
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: false
        filterBySpanID: false
        tags: [{key: deployment.environment.name, value: deployment_environment_name}]
        customQuery: true
        query: '{service_name=~"theo.*",$${__tags}} | trace_id="$${__trace.traceId}"'
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags: [{key: deployment.environment.name, value: environment}]
        queries:
          - name: Operation latency
            query: histogram_quantile(0.95, sum by(le, operation) (rate(theo_operation_duration_seconds_bucket{$${__tags}}[5m])))
      nodeGraph: {enabled: true}
