-- ============================================================================
-- Migration 0003: Memory tier tables
--
-- Creates all memory-related tables for Theo's knowledge graph, episodic
-- memory, core memory, user model, self model, and procedural memory (skills).
-- This is the schema foundation for Phases 5-8.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Shared trigger functions
-- ---------------------------------------------------------------------------

-- Auto-update updated_at on any row modification.
-- Attach to any table with an updated_at column.
CREATE OR REPLACE FUNCTION update_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Auto-populate search_text from body using english text search config.
-- Attach to any table with body (text) and search_text (tsvector) columns.
CREATE OR REPLACE FUNCTION update_search_text() RETURNS trigger AS $$
BEGIN
  NEW.search_text := to_tsvector('english', NEW.body);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Knowledge Graph: node
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS node (
  id          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind        text        NOT NULL
              CHECK (kind IN (
                'fact', 'preference', 'observation',
                'belief', 'goal', 'person', 'place',
                'event', 'pattern', 'principle'
              )),
  body        text        NOT NULL,
  embedding   vector(768),           -- pgvector, populated async by embedding service
  trust       text        NOT NULL DEFAULT 'inferred'
              CHECK (trust IN ('owner', 'owner_confirmed', 'verified', 'inferred', 'external', 'untrusted')),
  confidence  real        NOT NULL DEFAULT 1.0
              CHECK (confidence >= 0.0 AND confidence <= 1.0),
  importance  real        NOT NULL DEFAULT 0.5
              CHECK (importance >= 0.0 AND importance <= 1.0),
  sensitivity text        NOT NULL DEFAULT 'none'
              CHECK (sensitivity IN ('none', 'sensitive', 'restricted')),
  search_text tsvector,              -- populated by trigger from body
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  access_count   integer     NOT NULL DEFAULT 0,
  last_accessed_at timestamptz
);

-- HNSW index for vector similarity
CREATE INDEX IF NOT EXISTS idx_node_embedding ON node
  USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- GIN index for full-text search
CREATE INDEX IF NOT EXISTS idx_node_search_text ON node USING gin (search_text);

-- Kind filter for RRF queries and deduplication self-join
CREATE INDEX IF NOT EXISTS idx_node_kind ON node (kind);

-- Partial index for forgetting curve candidates
CREATE INDEX IF NOT EXISTS idx_node_last_accessed ON node (last_accessed_at)
  WHERE last_accessed_at IS NOT NULL;

-- Trigger: auto-populate search_text from body
CREATE OR REPLACE TRIGGER trg_node_search_text
  BEFORE INSERT OR UPDATE OF body ON node
  FOR EACH ROW EXECUTE FUNCTION update_search_text();

-- Trigger: auto-update updated_at on content changes only (not access tracking)
CREATE OR REPLACE TRIGGER trg_node_updated_at
  BEFORE UPDATE OF kind, body, trust, confidence, importance, sensitivity ON node
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- Knowledge Graph: edge
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS edge (
  id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id  integer     NOT NULL REFERENCES node(id) ON DELETE CASCADE,
  target_id  integer     NOT NULL REFERENCES node(id) ON DELETE CASCADE,
  label      text        NOT NULL,  -- extensible: 'related_to', 'caused_by', ...
  weight     real        NOT NULL DEFAULT 1.0
             CHECK (weight >= 0.0 AND weight <= 5.0),
  valid_from timestamptz NOT NULL DEFAULT now(),
  valid_to   timestamptz,           -- NULL = currently active
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Partial indexes for active-edge queries (the OR pattern in getActiveForNode
-- and graph traversal needs separate indexes; PostgreSQL BitmapOr merges them)
CREATE INDEX IF NOT EXISTS idx_edge_source_active ON edge (source_id)
  WHERE valid_to IS NULL;
CREATE INDEX IF NOT EXISTS idx_edge_target_active ON edge (target_id)
  WHERE valid_to IS NULL;

-- Prevent duplicate active edges between same node pair with same label
CREATE UNIQUE INDEX IF NOT EXISTS idx_edge_unique_active
  ON edge (source_id, target_id, label) WHERE valid_to IS NULL;

-- FK indexes (non-partial, required for FK enforcement on parent DELETE/UPDATE)
CREATE INDEX IF NOT EXISTS idx_edge_source ON edge (source_id);
CREATE INDEX IF NOT EXISTS idx_edge_target ON edge (target_id);

-- ---------------------------------------------------------------------------
-- Episodic Memory: episode
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS episode (
  id            integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id    text        NOT NULL,
  role          text        NOT NULL
                CHECK (role IN ('user', 'assistant')),
  body          text        NOT NULL,
  embedding     vector(768),
  search_text   tsvector,
  superseded_by integer     REFERENCES episode(id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_episode_session ON episode (session_id);
CREATE INDEX IF NOT EXISTS idx_episode_embedding ON episode
  USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
CREATE INDEX IF NOT EXISTS idx_episode_search_text ON episode USING gin (search_text);
CREATE INDEX IF NOT EXISTS idx_episode_superseded ON episode (superseded_by)
  WHERE superseded_by IS NOT NULL;

-- Partial index for consolidation queries (find un-superseded episodes by age)
CREATE INDEX IF NOT EXISTS idx_episode_unsuperseded ON episode (created_at)
  WHERE superseded_by IS NULL;

-- Trigger: auto-populate search_text from body (reuses update_search_text)
CREATE OR REPLACE TRIGGER trg_episode_search_text
  BEFORE INSERT OR UPDATE OF body ON episode
  FOR EACH ROW EXECUTE FUNCTION update_search_text();

-- Trigger: auto-update updated_at
CREATE OR REPLACE TRIGGER trg_episode_updated_at
  BEFORE UPDATE ON episode
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- Episode-Node Cross-Reference: episode_node
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS episode_node (
  episode_id integer NOT NULL REFERENCES episode(id) ON DELETE CASCADE,
  node_id    integer NOT NULL REFERENCES node(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (episode_id, node_id)
);

CREATE INDEX IF NOT EXISTS idx_episode_node_node ON episode_node (node_id);

-- ---------------------------------------------------------------------------
-- Core Memory: core_memory
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS core_memory (
  slot       text        PRIMARY KEY,  -- 'persona', 'goals', 'user_model', 'context'
  body       jsonb       NOT NULL DEFAULT '{}',
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE TRIGGER trg_core_memory_updated_at
  BEFORE UPDATE ON core_memory
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Seed the 4 core memory slots
INSERT INTO core_memory (slot, body) VALUES
  ('persona', '{}'),
  ('goals', '{}'),
  ('user_model', '{}'),
  ('context', '{}')
ON CONFLICT (slot) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Core Memory Changelog: core_memory_changelog
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS core_memory_changelog (
  id          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot        text        NOT NULL REFERENCES core_memory(slot),
  body_before jsonb       NOT NULL,
  body_after  jsonb       NOT NULL,
  changed_by  text        NOT NULL,  -- actor
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_core_memory_changelog_slot ON core_memory_changelog (slot);

-- ---------------------------------------------------------------------------
-- User Model: user_model_dimension
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_model_dimension (
  id             integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text        NOT NULL UNIQUE,
  value          jsonb       NOT NULL DEFAULT '{}',
  confidence     real        NOT NULL DEFAULT 0.0
                 CHECK (confidence >= 0.0 AND confidence <= 1.0),
  evidence_count integer     NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE TRIGGER trg_user_model_dimension_updated_at
  BEFORE UPDATE ON user_model_dimension
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- Self Model: self_model_domain
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS self_model_domain (
  id          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text        NOT NULL UNIQUE,
  predictions integer     NOT NULL DEFAULT 0
              CHECK (predictions >= 0),
  correct     integer     NOT NULL DEFAULT 0
              CHECK (correct >= 0 AND correct <= predictions),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE TRIGGER trg_self_model_domain_updated_at
  BEFORE UPDATE ON self_model_domain
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- Procedural Memory: skill
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS skill (
  id                integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text        NOT NULL,
  trigger_context   text        NOT NULL,
  trigger_embedding vector(768),
  strategy          text        NOT NULL,
  success_count     integer     NOT NULL DEFAULT 0,
  attempt_count     integer     NOT NULL DEFAULT 0,
  success_rate      real        GENERATED ALWAYS AS (
    CASE WHEN attempt_count = 0 THEN 0.0
         ELSE success_count::real / attempt_count
    END
  ) STORED,
  version           integer     NOT NULL DEFAULT 1,
  parent_id         integer     REFERENCES skill(id) ON DELETE SET NULL,
  promoted_at       timestamptz,
  domain            text[]      NOT NULL DEFAULT '{}',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- HNSW index for trigger similarity search
CREATE INDEX IF NOT EXISTS idx_skill_trigger_embedding ON skill
  USING hnsw (trigger_embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- Active (non-promoted) skills for retrieval
CREATE INDEX IF NOT EXISTS idx_skill_active ON skill (updated_at DESC)
  WHERE promoted_at IS NULL;

-- Version lineage
CREATE INDEX IF NOT EXISTS idx_skill_parent ON skill (parent_id)
  WHERE parent_id IS NOT NULL;

-- Trigger: auto-update updated_at
CREATE OR REPLACE TRIGGER trg_skill_updated_at
  BEFORE UPDATE ON skill
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
