---
apiVersion: 1
contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram
        type: telegram
        settings:
          bottoken: ${TELEGRAM_ALERT_BOT_TOKEN}
          chatid: ${TELEGRAM_ALERT_CHAT_ID}
          message: |
            [${severity}] ${alertname}
            ${summary}
            ${runbook_url}
  - orgId: 1
    name: email
    receivers:
      - uid: email
        type: email
        settings:
          addresses: ${ALERT_EMAIL}
